### ISSUE TITLE
Al hacer zoom al alejarse de la pantalla los cluster no se vuelven a agrupar, solo cuando se aleja de la grafica, zoom out.

### ISSUE THREAD

**Issue by DaimerCuellar** [Leaflet/Leaflet.markercluster#1013]
Usando versiones actualizadas del folleto, navegadores como chrome, firefox o Opera, reprudecen este problema.
![Captura de pantalla de 2020-10-24 15-58-30](https://user-images.githubusercontent.com/44903114/97093505-11df4780-1612-11eb-9043-5cffdeaa22e0.png)

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
¿"reprudecen"? ¿Qué significa "reprudecer"?

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
