### ISSUE TITLE
MarkerClusterGroup.clearLayers not correctly removing listeners because incorrect use of 'this' inside eachLayer

### ISSUE THREAD

**Issue by JDRitchey** [Leaflet/Leaflet.markercluster#1060]
- [X] I'm reporting a bug, not asking for help
- [X] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----

There is a mistake on line 443 of MarkerClusterGroup.js
https://github.com/Leaflet/Leaflet.markercluster/blob/31360f226e1a40c03c71d68b016891beb5e63370/src/MarkerClusterGroup.js#L443

'this' will refer to the Window object.  this is causing a warning to display when this plugin is used with Leaflet 1.8.
presumably event listeners are not being removed as a consequence.

**Comment by IvanSanchez** [comment]
There's no mistake, since there's a second parameter to `eachLayer` (in line 445) used as the context of the inline function.

> this is causing a warning to display when this plugin is used with Leaflet 1.8.

Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour? (minimal, no frameworks, just leaflet and leaflet.markercluster). Unless there's a reproducible warning message, this bug report will be closed.

**Comment by JDRitchey** [comment]
Sorry, you're right, it looks like I actually have an out-of-date copy.  the second this argument is not passed into eachLayer in my copy.  should be fine to close this issue then.
