### ISSUE TITLE
[BUG] leaflet.markercluster 1.5.3 version issue with leaflet 1.9.2

### ISSUE THREAD

**Issue by vogloblinsky** [Leaflet/Leaflet.markercluster#1076]
## How to reproduce

- Leaflet version I'm using: 1.9.2
- Leaflet.MarkerCluster version I'm using: 1.5.3
- Browser (with version) I'm using: Chrome 105
- OS/Platform (with version) I'm using: macOS 12.6
- getting started code for clustering

## What behaviour I'm expecting and which behaviour I'm seeing

![image](https://user-images.githubusercontent.com/2841805/194110908-a1deea06-e3e9-4599-9ced-408cf9ef6f88.png)

Same code works fine with Leaflet 1.9.1

**Comment by ykzeng** [comment]
this seems like an issue due to the removal of global "L" in the leaflet parent lib, if that is the case you may find some hotfixes here #874 for now. In the meanwhile, we will release a new version that's compatible with latest leaflet soon. if these hotfixes did not solve the issue, please reopen with a more concrete code example.

**Comment by Ugoku** [comment]
@ykzeng it's been almost 5 months since the comment above, but no new version since then. Any idea when we can expect a new version?
