### ISSUE TITLE
Manual method to start clustering

### ISSUE THREAD

**Issue by klimashkin** [Leaflet/Leaflet.markercluster#138]
Hello!
Faced with such a problem. When user change zoom (from 18 to 17, for example), I requests new data from server, because I have data only for visible bound.
So, when user changed zoom, MarkerCluster immideatly start re-clustering, then I add new markers to it (witch received from server for new bound) and then MarkerCluster start another re-clustering.
It's very bad for performance.
Can I call re-clustering method manually, only after new markers was added? It's very necessary feature, otherwise I can't use your great plugin..

**Comment by Filson14** [comment]
Hi! I have quite simillar issue.
I'm using data pre-clustered on server side. Each element is added to leaflet map as a marker with value and next added to markerClusterGroup. Data is loaded on every 'map move' (zoom in/out, map moving etc). Precision of server-side aggregation depends on map zoom, so the problem is when the precision changed and new-loaded markers are in different locations than before zooming. Is it possible to prevent clustering or do it in timeout maybe?

The problem, step by step (hope it will be easier):
1. Map zoom is 15, markers are clustered on the map.
2. I zoom out the map, precision is decresed. Start to download data from server. At the same time, clustering is triggered, clusters on map are joined, moved to another places (animation is showing that - I use "animation: false" so, I think, that shouldn't happen?!)
3. Data finished loading, previous markers are cleared and new ones are added - in, again, different locations.

During that process, the animation of clustering mislead the user because of different locations and numbers on clusters. What is the way to prevent this? Like I said, I add "animation: false" parameter to markerClusterGroup.

**Comment by danzel** [comment]
No, what you want is not possible.

**Comment by Filson14** [comment]
Ok, thanks for the reply. I will have to live with the for now or find a way around.
