### ISSUE TITLE
Feature suggestion: add option for marker cluster colors

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.markercluster#255]
it would be very useful it the colors for marker clusters (.marker-cluster-*) could also be set via an option

**Comment by sevamoo** [comment]
Hi
I am wondering if it would be possible to color the MarkerClusters based on some aggregate features of the markers belonging to each cluster? I mean instead of count use some mean values of the markers. Let say we have a price attribute for each market and now we are interested to color clusters based on the average or median price.
Thanks a lot.

**Comment by curtains23** [comment]
Is there a  comprehensible tutorial for this action anywhere? Been slamming my head against this problem for a while now..

**Comment by sevamoo** [comment]
@curtains23 Not, sure exactly if this is what you want. 
Look at this map [here](http://www.keylead.ch/map). Click Show.
But The way I handle it is [here](https://gist.github.com/sevamoo/2442e9463c80d1b3ef276bf42ca4f509#file-markercluster_color-js)
hope it helps.

**Comment by mawg** [comment]
> But The way I handle it is [here](https://gist.github.com/sevamoo/2442e9463c80d1b3ef276bf42ca4f509#file-markercluster_color-js)
> hope it helps.

A link to a Plunker would also help ;-)  I will read through the code & figure it out, so thanks very, very much for that. Others will do the same, but it would have been nice to see the code in action before reading it.
