### ISSUE TITLE
No longer works with leaflet master version

### ISSUE THREAD

**Issue by danzel** [Leaflet/Leaflet.markercluster#289]
Broken by Leaflet/Leaflet@789c35601775d47cbbd4747aa586b78a94c787c1
Hopefully an easy fix

**Comment by sookoll** [comment]
Still / again doesn't work. Take leaflet master and markercluster master, build them, and it gives an error to leaflet-src.js line 135 on method trim. It seems, that root of the cause is here:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L46

L.FeatureGroup.EVENTS are undefined. Any hints how this will work? If EVENTS property is removed from featuregroup, how to fixed this?
