### ISSUE TITLE
Algorithm for clustering

### ISSUE THREAD

**Issue by sayush** [Leaflet/Leaflet.markercluster#401]
I just started using the Markercluster and it does a great job. I have a simple question, when you mouseover a cluster, it highlights a polygon - how is that generated and what do they represent? It would be great if somebody could also point out the underlying clustering algorithm. Thanks.

**Comment by kirantpatil** [comment]
I would like to implement this algorithm in server side, so I picked python since it has plethora of algoritms.

May I know the availability of the "Greedy clustering algorithm" in python ?

I couldn't find the algorithm with that name in python.

Anyone please help me to get the algorithm either is python, rust or go.

**Comment by kirantpatil** [comment]
I found one in python which is https://github.com/reza-asad/Single-Link-Clustering.

Can you please confirm, if it is the same algorithm used here ?

Thanks.

**Comment by kirantpatil** [comment]
Also found below one, please let me know the matching algorithm

https://pypi.python.org/pypi/AgglomCluster/2.0.4
