### ISSUE TITLE
Not working removeOutsideVisibleBounds

### ISSUE THREAD

**Issue by denny123** [Leaflet/Leaflet.markercluster#429]
I have markers with labels like:

http://code.metager.de/source/xref/osm/osrm/web/WebContent/base/leaflet/L.LabelMarker.js
http://code.metager.de/source/xref/osm/osrm/web/WebContent/base/leaflet/L.LabelMarkerIcon.js

and

```
       var via_points = new L.MarkerClusterGroup({
             maxClusterRadius: 30,
             disableClusteringAtZoom: true,
             removeOutsideVisibleBounds: false
       });

      var icon_via_points = new L.LabelMarkerIcon({
            iconUrl: '/needleleftyellow.png',
            iconAnchor: [27, 44]
      });
```

and add markers like:

```
          for (var g=1; g<loc_arr.length-1; g++) { //>
            var marker=new L.LabelMarker([loc_arr[g][0], loc_arr[g][1]],{icon: icon_via_points, draggable: true});
            marker.on({
               mousedown: mousedown_via_points,
               drag: drag_via_points,
               dragend: dragend_via_points,
               mouseover: mouseover_via_points,
               mouseout: mouseout_via_points
            });
            via_points.addLayer(marker).addTo(map);
            marker.setLabel(g);
          };
```

and after zoom map outside markers and zoom map inside markers(markers redraw!!!) then my labels(in markers that not see after zoom) not show.

Working if set like:

```
        _getExpandedVisibleBounds: function () {
               if (!this.options.removeOutsideVisibleBounds) {
                       return this./*_map.*/getBounds();
               }
```

but after add new markers - they after zoom map not show or show...

leaflet v0.7.3

**Comment by openfirmware** [comment]
I was also having an issue with disabling `removeOutsideVisibleBounds` and having markers/clusters near the edges of the map disappear. This is especially pronounced when using an alternate map projection with Leaflet because the rectangular bounding box returned by `map.getBounds()` assumes a rectangle in Mercator projection. The result is markers in the current view that are close to certain edges of the window will be hidden.

[I tested a fork](https://github.com/GeoCENS/Leaflet.markercluster/commit/8b360cbe9b7edb50bcf73ceab52f384a40f28a8c) with the following commit reverted: ba0c2146cac507a7592a7ddc827e18b662514bda. It works the way I would expect, where the bounding box for all the markers/clusters is used instead of the bounding box for the map's current view when `removeOutsideVisibleBounds` is false.

Is there a source on why that commit was made? Was there an issue it was fixing that I have inadvertently broke in my fork?

**Comment by danzel** [comment]
Not sure, if we have no markers then this.getBounds would probably be invalid.
