### ISSUE TITLE
Popup not working with circlemarker in cluster

### ISSUE THREAD

**Issue by kjetila** [Leaflet/Leaflet.markercluster#431]
Hi,

I am having problems getting the popup in the markercluster to work with geojson, pointToLayer and circleMarker functionality. The last feature will popup as expected, however the others will not. 

I have made a minimal example for this in jsfiddle: http://jsfiddle.net/kjeander/aue7uhe2/1/

If I remove the pointToLayer part and only use normal markers it seem to work fine. 

If I am doing anything wrong, please advice me :-)

Thanks,
Kjetil

**Comment by danzel** [comment]
![image](https://cloud.githubusercontent.com/assets/393086/5731776/7467c3b0-9bec-11e4-8834-c7d0e8ec980d.png)
Works for me?

**Comment by danzel** [comment]
Your circles will be appearing below the marker cluster icon I expect.

**Comment by kjetila** [comment]
Yes, the circles are drawn nicely under the cluster and the popup works fine for the last point of the geojson. However if I try to click for popup on the first point 'TEST POINT 1' it will not popup.

**Comment by danzel** [comment]
Have you tried larger circles?

**Comment by mmdolbow** [comment]
Any resolution on this? I've found a similar issue.

**Comment by mmdolbow** [comment]
I was looking for a resolution on this - it seems that the app can get confused about the clickability of the circles if they are too close to the center of the cluster. So, adding the spiderfyDistanceMultiplier option with a value of 2 or more seems to help. I show that in the following fiddle:
https://jsfiddle.net/mmdolbow/aue7uhe2/7/

Still seems like a bug - but I think this workaround is adequate.

**Comment by ghybs** [comment]
Hi,

Old issue, but just for other people who might get the same problem: this is due to Leaflet 0.7.x which renders vector layers (like circleMarker and other polylines) in the map [overlayPane](http://leafletjs.com/reference.html#map-overlaypane), whereas the cluster icon resides in the [markerPane](http://leafletjs.com/reference.html#map-markerpane), which is always _above_ the overlayPane.

The most simple workaround as suggested by mmdolbow above is to use a `spiderfyDistanceMultiplier` option value > 1 to increase the distance between the vector layers and the cluster, so that they get out from below the cluster icon.

More sophisticated resolution would require changing the spiderfier configuration, as shown in the below updated jsfiddle for example:
http://jsfiddle.net/aue7uhe2/15/
This highlights the [trick](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js#L36) that offsets the circle a few pixels down, so that standard markers (the blue icon) are centered around the cluster icon, but which do not apply for other types of markers (like circleMarkers in this case).

I have heard that Leaflet 1.0 would provide more control about those panes (Leaflet/Leaflet#1742). With such a feature, MCG could then force spiderfied layers to be shown on top of everything (including above the icon of cluster they come from), rather than being stuck with the map predefined panes.
That would definitely be a more elegant solution.

**Comment by akleinwaechter** [comment]
This problem is still not fixed in the 1.0.0. Beta. You can*t open Popups with spiderfied Circlemarkers. All the tricks above won't work anymore.

**Comment by ghybs** [comment]
Hi,

Thank you for your message.

Please can you kindly explain why you say that "tricks above won't work anymore"?
Looks to me that `spiderfyDistanceMultiplier` option is still a valid workaround.

Updated JSFiddle: https://jsfiddle.net/aue7uhe2/17/

**Comment by akleinwaechter** [comment]
I really have no clue. I implemented it like you did and it doesn't work. I try to make a fiddle the next days.
Thanks.

**Comment by prasadKodeInCloud** [comment]
+1

**Comment by prasadKodeInCloud** [comment]
Popup is broken even in  [marker-clustering-geojson example](https://github.com/Leaflet/Leaflet.markercluster/blob/master/example/marker-clustering-geojson.html) 
Any permanent fix for this issue?

**Comment by prasadKodeInCloud** [comment]
Hi @ghybs,

I tried your example for a "MultiPoint" Feature collection. Seems popup is not working in this scenario. Can I know whether its not supported for "MultiPoint" features? I just updated your jsfiddle
https://jsfiddle.net/aue7uhe2/18/

Thanks!

**Comment by ghybs** [comment]
Hi @prasadKodeInCloud,

As for the [marker-clustering-geojson example](https://github.com/Leaflet/Leaflet.markercluster/blob/master/example/marker-clustering-geojson.html), looking at the page code, I see that there are 4 markers (`eye1`, `eye2`, `nose` and [another one](https://github.com/Leaflet/Leaflet.markercluster/blob/master/example/marker-clustering-geojson.html#L49)) and a polyline (`mouth`) without bound popup. All other features have a working popup for me. Therefore all seems to work as expected as far as I can tell.

As for your JSFiddle with `MultiPoint` geometry type, what happens is that Leaflet applies `onEachFeature` on the `MultiPoint` group (it creates a Feature Group containing each individual point), not actually to your individual points (i.e. circle markers).
Without MCG, it works because your GeoJSON group is added to the map, and clicking on your circle markers propagates the click event to the GeoJSON / Feature Group, which opens the popup.
But with MCG, it stripes out any group and adds only the individual layers (i.e. circle markers in your case) to the group and map. Because the Feature Group itself is not on map, I guess it cannot receive the click events, hence it cannot open any popup.
Simply binding the popup within the `pointToLayer` option instead of `onEachFeature` ensures that each point feature has an individual popup, instead of a popup delegated to a potential group that will be stripped out by MCG.

Updated JSFiddle: https://jsfiddle.net/to9g5ebs/3/

**Comment by ghybs** [comment]
Hi,

This issue was raised again on [GIS SE](https://gis.stackexchange.com/questions/259376/reading-attribute-popup-information-from-cluster-presented-points-in-the-map-gen/259538?noredirect=1#comment410798_259538), specifically when Leaflet and Leaflet.markercluster are used by [qgis2web](https://github.com/tomchadwin/qgis2web) to automatically generate a web-ready map.

The `spiderfyDistanceMultiplier` workaround has been [discussed](https://github.com/tomchadwin/qgis2web/issues/505) in qgis2web repo and [implemented](https://github.com/tomchadwin/qgis2web/releases/tag/v2.31.0).

However, it would be interesting to implement a proper fix directly in Leaflet.markercluster.

An idea could be to increase by default the minimum spiderfication leg distance, so that they extend outside the cluster default icon in all situations.

In case the app developer provides his/her own cluster icon (using the `iconCreateFunction` option), this strategy might still fail, and the app developer could then resort to using `spiderfyDistanceMultiplier` option workaround again.
