### ISSUE TITLE
Fire a popup for a cluster group

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet.markercluster#46]
In our leaflet map, we have a table next to it that lists each of the points. When a row in the table is clicked, we would like to have a popup displayed over the cluster the point is in (or zoom to the point in the cluster and have a popup).

Before it worked fine because we didn't have clustering.

Is there a way to find the cluster of a given marker and then show a popup where the cluster is?

**Comment by chanurahemal** [comment]
First of all i would like to thanks for making this wonderful plugin

I want know what are the markers which are visible(as a single marker) without clustering?
as an example i have makersclustergroup which is have 6 markers and when initially load it, it shows 4 markers as a cluster one and other 2 markers are separated and shows individually. so i need to know which markers are outside that cluster?(basically i need to get that 2 markers which lay on outside cluster icon)

(keep in mind, these all markers are in one makersclustergroup )
your help is really appreciated.

Thank you

**Comment by danzel** [comment]
@chanurahemal if you iterate over the layers in ```markerClusterGroup._featureGroup``` that should do it.

**Comment by chanurahemal** [comment]
Hi,
Thank you very much for quick replay @danzel 
But when i get markerClusterGroup._featureGroup, it returns all 6 features, not only 2 markers from outside clustered.

**Comment by danzel** [comment]
You sure?
Pretty certain it should return whatever is visible on the map right now, so if it is 2 clusters and 2 markers you should get 4 'markers' and you'll need to check what kind they are (```L.MarkerCluster``` for clusters)

**Comment by chanurahemal** [comment]
i have all 6 markers and 4 markers are shown as one cluster and other 2 are shown as separate markers. when i get markerClusterGroup._featureGroup, it returns all 6 markers.

extremely sorry if i bother you :(

**Comment by chanurahemal** [comment]
Hi @danzel,
I think i had done a mistake in my implementation. I will correct it and let you know how it went. really appreciated your help

Cheers

**Comment by chanurahemal** [comment]
Hi @danzel 

Yes, it is working fine. Thanks a lot

**Comment by chanurahemal** [comment]
i am using "clusterclick" event on cluster group to execute a function like this.
$this.markerClusterGroup.on('clusterclick', function (a) {
                $this._setPercentageCircle();
            });
i am doing executing same setPercentageCircle() on "zoomend" event as well, since sometimes user doesn't click cluster but zooming manually. that function looks like this: 

$this.map.addEventListener('zoomend', function(e){
                $this._setPercentageCircle();
            });

my requriement is stop executing zoomend event, when user clicks on a cluster. At the moment both will be executed as when click on a cluster, it zooms the map automatically. How do i get done this? When i check event on zoomend, it doesn't have stop propergation.

Thank you

**Comment by ghybs** [comment]
Hi,

What exactly are you trying to achieve?

If you want to execute your function on cluster click event and prevent zooming, option `zoomToBoundsOnClick: false` should do it.

If you want to execute your function when cluster size changes (due to map zoom or user click on cluster, and markers being unclustered), are you sure your listener on `zoomend` is not enough? There are some cases where clicking on a cluster does not trigger zooming (when already on maxZoom). For those, event `spiderfied` should be good. You could even replace `map.on("zoomend", fn)` by `clusterGroup.on("animationend", fn)` for consistency.

@dsifford, danzel's above solution about polling `markerClusterGroup._featureGroup` could be a more elegant solution for your issue #558 if you want only markers in the view port.

Hope this helps.

**Comment by chanurahemal** [comment]
Actually as i mentioned above i have a function called _setPercentageCircle(). I need to trigger this function when click on cluster. Further i need to execute this function when user manually zoom the map as well.So when i set it on zoomend event like this 

$this.map.addEventListener('zoomend', function(e){
$this._setPercentageCircle();
});

it works properly on zooming. But my problem is as i trigger this event on cluster click as well it trigger twise as when cluster click it zoom automatically. so my requirement is when user click cluster, it should trigger my function, but only one time. when user zoom it manually, then again my function just trigger only one time.

**Comment by ghybs** [comment]
Hi,

Maybe I missed something…

It seems to me that if you are happy with executing your function when the
user zooms on the map, why would you need to execute it when the user
clicks on the cluster?

When clicking on the cluster, just let the default behaviour of cluster
expanding and zooming, which will then execute your zoomend callback?

**Comment by chanurahemal** [comment]
First of all i would like to thanks you all for your valuable inputs.
@ghybs yes i tried that way, but then it is not consistent the functionality and sometimes that function is not being triggered when i click on cluster mark

Thanks.
