### ISSUE TITLE
This is company selling Leaflet.markercluster for $39.00 USD?

### ISSUE THREAD

**Issue by tforward** [Leaflet/Leaflet.markercluster#507]
http://regionbound.com/

**Comment by RikdeBoer** [comment]
Hi,
I recently added an interface to RegionBound for my Drupal CMS module http://drupal.org/project/ip_geoloc.
[BTW, there has been a Drupal interface to Leaflet.markercluster for years: https://www.drupal.org/project/leaflet_markercluster]

Let me share what I know about RegionBound.

RegionBound are NOT selling Leaflet.markercluster. As is common in Open Source, they forked it and then added significant features (region-awareness, tight coverage outline and region-aware in-situ aggregations) and are selling the added value.

This is both common and legal. 

Think of RedHat. Or of the system you and I are using right now: Git
Using your words, one could say that GitHub are "selling" Git. 

One can wonder, whether it is fair.
Personally I think that the genius of Linus Torvalds deserves to be a billionaire for what he has given us. But I don't think he is. And danzel deserves to be a millinonaire to.

danzel released Leaflet.markercluster under the MIT License which means that he allowed anyone to do just about anything with it, including monetising it, provided you give credit to the original developer. Which RegionBound do on their home page and at the top of the code.

Personally I am not a great fan of the way that Open Source software has panned out. To me it seems we have ended up with a small group of developers producing software that is consumed by much larger groups of consumers who pay nothing to the developers, but reap the benefits of the software for both personal and corporate use. 

When you publish a book or a song you receive money for that. Sometimes quite a lot of money.
When you publish Open Source software you get nothing.

To me that does not sound fair and not sustainable. Yet this is the attitude of the average Open Source punter. The moment they have to pay a couple of dollars for ANYTHING they run.

It is probably one of the reasons, apart from its superb quality, why the Leaflet.markercluster plugin has become so popular. Because it is free. If danzel had charged for it, it may still have been just as obscure as RegionBound is and will remain.

Rik

**Comment by danzel** [comment]
Might be nice if they send me some money *hint hint* :)
But they are totally within their rights to do it.

Region-aware clustering is a cool feature too!

**Comment by jeffrycopps** [comment]
@Danzel, Adding the region aware clustering feature within Leaflet.markercluster will be very helpful.

**Comment by mattgrande** [comment]
@danzel - Do you have a donate link? My new years resolution last year was to monetarily support more open source tools that I use, but I never really followed through on it as much as I should have... There's 14 days left for me to make good on my resolution :smile:

**Comment by danzel** [comment]
Donate to a charity on my behalf if you would like :-)
I usually work on markercluster during work hours, so I'm already getting paid for it.
