### ISSUE TITLE
Marker cluster is not working with leaflet-image functionality.

### ISSUE THREAD

**Issue by mayuri2601** [Leaflet/Leaflet.markercluster#524]
Hi,

I have used leaflet-image functionality in my code to take the snapshot of the map.
 And i am trying to take the snapshot after adding the marker cluster group, but I am getting the following errorr :-

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

Thanks for your return on this point!

**Comment by lexusburn** [comment]
+1

**Comment by atdiff** [comment]
Has anyone gotten leaflet-image and markercluster to work successfully together?

**Comment by ghybs** [comment]
Hi,

If my understanding is correct, Leaflet.markercluster does not work with [leaflet-image](https://github.com/mapbox/leaflet-image) because of the `L.divIcon` used by [default MCG `iconCreateFunction`](https://github.com/Leaflet/Leaflet.markercluster/blob/15ed12654acdc54a4521789c498e4603fe4bf781/src/MarkerClusterGroup.js#L554)?

leaflet-image:

> This library does not rasterize HTML because browsers cannot rasterize HTML. Therefore, L.divIcon and other HTML-based features of a map, like zoom controls or legends, are not included in the output, because they are HTML.

In that case, you would "just" need to specify a custom `iconCreateFunction` option to MCG, which would build a marker that is not based on an `L.divIcon` (for example you could try a circle marker). As for the children count, you will have to find a way to include it as a vector, or get rid of it.

Hope this helps.
