### ISSUE TITLE
If a cluster is Spiderfied when cluster layer markers are removed from the map, the lines remain

### ISSUE THREAD

**Issue by metajungle** [Leaflet/Leaflet.markercluster#525]
When markers are removed from a cluster that is "spiderfied", the spider lines remain on the map. This is probably related to #53 and #54. 

This can be tested and replicated by using the old test code in "remove-when-spiderfied.html". Just update the HTML and reference to latest build in the "dist" folder. 

Please let me know if I missed anything. 

![image](https://cloud.githubusercontent.com/assets/2658733/8527138/f6a27efa-23d8-11e5-8142-8cdcc7d5fdbf.png)

**Comment by olive380** [comment]
Yes, I agree with you, the bug is still there.

On the same subject, there is another bug, but only for markers created using L.geoJSON.

To watch this bug, let's create 'doit4' :
L.DomUtil.get('doit4').onclick = function () { markers.removeLayer(markersList[0]); };

If you create the markers by using: m = new L.Marker([lat, lng]);
everything is fine when your click the button when spiderfy the cluster.

But if you create the markers using the following lines:
geoJsonFeature = { "type": "FeatureCollection", "features": [ { "type": "Feature", "geometry": { "type": "Point", "coordinates": [lng, lat] } } ] };
m = L.geoJson(geoJsonFeature, { pointToLayer: function (feature, latlng) { return L.Marker(latlng); } } );
then spider lines remain on the map.

Hope this will be useful for solving the issue.

**Comment by danzel** [comment]
olive380 thinks this is fixed by the rebuild hopefully.
Please reopen if not.

**Comment by danzel** [comment]
Bah, I haven't rebuilt this. TODO

**Comment by danzel** [comment]
Doing a new build today for #528

**Comment by nothingisnecessary** [comment]
Thanks for fix! I know I am late to party but I didn't see anybody else confirm - this works for me when adding and removing L.geoJson layers while spiderfied, regardless of zoom level.
