### ISSUE TITLE
problem with bower package

### ISSUE THREAD

**Issue by badoet** [Leaflet/Leaflet.markercluster#549]
when installing using bower version 0.4.0
the MarkerOpacity.js file is missing. causing error "marker.setOpacity is not a function" to occur

**Comment by IvanSanchez** [comment]
Apparently Bower is pulling [v0.4](https://github.com/Leaflet/Leaflet.markercluster/releases/tag/0.4) instead of [v0.4.0-hotfix.1](https://github.com/Leaflet/Leaflet.markercluster/releases/tag/v0.4.0-hotfix.1), which does include the missing file.

You can work around the issue by running `bower install leaflet.markerclusterer#0.4.0-hotfix.1`.

@danzel, thoughts?

**Comment by badoet** [comment]
y not bump it to 0.4.1? it would be a more elegant solution IMO

**Comment by danzel** [comment]
That is a not really a release release. It is just whatever was in the code base at some time.
Will probably look at doing a more official release soon with leaflet 1.0 coming up... ;)
