### ISSUE TITLE
Bind poppup to each MarkerCcluster`s marker

### ISSUE THREAD

**Issue by SultanPro** [Leaflet/Leaflet.markercluster#566]
Hi, I have every marker added to the markerclusterer markers and I want to just bind poppup to each marker , like when you are zooming map and click markers here should poppup appear,but here clusters not working just markers without clusters
Here Loop:
       var me = this;
        var marker = new L.MarkerClusterGroup();
        var store = Ext.getStore('Person.PersonStore');
        for (var i = 0; i < store.data.items.length; i++) {
            if (store.data.items[i].data.position != null) {
                var lat = store.data.items[i].data.position.lat;
                var lng = store.data.items[i].data.position.lng;
                var position = {
                    lat: lat,
                    lng: lng
                };
               marker = new L.Marker(position).bindPopup('<div>' + "sssss" + '</div>');
                 map.addLayer(marker);
        }
How to make them bind poppup and when you click to marker here poppup appear?
Thanks
I have read about this but they used custom marker

**Comment by Quentin22** [comment]
I have got this code which work for me. I use a .geojson file convert into js variable to get coordinates of markers :
```javascript
  // We create each marker with its popup from geojson variable
  function onEachFeature(feature, layer) {
    var popupText = feature.properties.name;
    layer.bindPopup(popupText);
  }

  var geo = L.geoJson(geojson, {
    onEachFeature: onEachFeature
  });

  markers = new L.MarkerClusterGroup();
  markers.addLayer(geo);
  map.addLayer(markers);
```

**Comment by ghybs** [comment]
Hi,

Please note that whenever you need help for your project, the most appropriate place would probably be the [Leaflet forum](https://groups.google.com/forum/#!forum/leaflet-js).

Then if your code is fine but you know the problem comes from the library, open an issue here.

For your application, be noted that you have **markers** and **groups**. The latter can hold markers and other groups. All are considered as "layers".
MarkerClusterGroup, FeatureGroup, LayerGroup are such groups.

Create your markers (the ones that have latitude-longitude position), add them to a group (`group.addLayer(marker)`), and add the group to your map (`map.addLayer(group)`).

Hope this helps.

**Comment by Quentin22** [comment]
Thanks for the Leaflet forum.

I don't if the problem comes from the library or if I don't know how to use it. ^^

To create markers I think I did like you are saying :
 - Markers are "geo" variable
 - Group is "markers" variable (MarkerClusterGroup)

Maybe I have to create my own CSS style for cluster with two state "cluster" : blue color and "clusterError" : red color ? Is it possible to do something like that ?

**Comment by SultanPro** [comment]
Thank you for helping me but can you give me hand again,my issue is I add markers with poppup then when I click list it shows popup of marker of apprepricate marker:
                        cellclick: this.ListClick,
ListClick: function(grid, rowIndex, cellIndex, e) {
                        var me = this;
                        var time = new Date(e.data.position.date);
                        var date = new Date(time);
                        var mymarker = L.marker([e.data.position.lat, e.data.position.lng]).openPopup();
                         // var popup = L.popup().setLatLng(e.data.position.lat, e.data.position.lng).openOn(me.map);

                        me.map.panTo(mymarker.openPopup());
}
It is only move to marker but poppup doesnt work I have implememt popup on another method
Thanks in advance

**Comment by ghybs** [comment]
Sultan,

See my answer in the forum:
https://groups.google.com/d/msg/leaflet-js/KU47UdxlpAE/ppopkObVEgAJ

Cheers
