### ISSUE TITLE
Cannot read property '_icon' of undefined

### ISSUE THREAD

**Issue by mfc-julius** [Leaflet/Leaflet.markercluster#580]
I can't reproduce this bug, but I get notifications from time to time on Opbeat, when 'animationend' is fired in  L.MarkerClusterGroup.include.L.DomUtil.TRANSITION._animationEnd, and `showMarker` method tries to check `if ((layer._icon || layer.__parent._icon) && !this._inZoomAnimation)`, and apparently __parent does not exist (see StackTrace at the bottom).

I'm not very familiar with Leaflet's code, but if the __parent is not always available, would it be worth checking `if ((layer._icon || (layer.__parent && layer.__parent._icon)) && !this._inZoomAnimation)`?

StackTrace:
L.MarkerClusterGroup.include.L.DomUtil.TRANSITION._animationEnd
L.Mixin.Events.fireEvent
showMarker
?

**Comment by ghybs** [comment]
Hi,

It seems that you are using the [zoomToShowLayer](https://github.com/Leaflet/Leaflet.markercluster#other-methods) method?

Normally all point objects (this includes markers) within an MCG should always have their `__parent` property set.
Furthermore, within the `zoomToShowLayer` method, all ways that call `showMarker` already check for or use `layer.__parent`, so it would be strange that this property "disappears"...

Please have you checked whether the layer that is passed as argument of `zoomToShowLayer` is a child of the MCG?
Is there any chance that the layer is removed from the MCG at the same time?
Note that if you move it, it is actually removed and added back.

Hope this helps.

**Comment by ghybs** [comment]
Maybe this is related to #530 and #397?

**Comment by mfc-julius** [comment]
Thanks for you answer.

I don't really know if it might be related, because even on those issues it's not really clear what's the real issue.

I use `zoomToShowLayer` in two places on my code:

```
// triggered manually by pressing a button "zoom to feature"
if (child && mainLayer.getVisibleParent(child) instanceof L.MarkerCluster) {
  mainLayer.zoomToShowLayer(child, function () {});
}
```

So this does the check you mentioned (also not the callback function I must provide, the issue was opened here: https://github.com/Leaflet/Leaflet.markercluster/issues/503).

Also:

```
// triggered when accessing feature to show it on the map
if (child && mainLayer.getVisibleParent(child) instanceof L.MarkerCluster) {
  if (layer.feature.deflated && !landingWithCenter) {
    visualization.fitToLayerBounds(child);
  } else if (!landingWithCenter || zoom === 19) {
    leaflet.layers.mainLayer.zoomToShowLayer(child, function () {});
  }
}
```

It might be that the feature gets removed at the same time, because I use modified https://github.com/oliverroick/Leaflet.Deflate (modification is needed for this to work with clusters). So, when the method gets called, on a feature that is inside the cluster but is actually deflated polygon or polyline, when zooming to it, at the end it will be converted from marker to the actual shape.

For checking and converting to/from created marker I use on 'zoomend', which is also used by this plugin.

**Comment by ghybs** [comment]
Hi,

Well you are probably on it with Leaflet.Deflate.

If you actually remove your marker from MCG (besides from the map or not),
then the marker [loses](
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L622)
its `__parent` property, and it will not get a new one because it is
replaced by another object.
The `showMarker` callback does not know it should now refer to that other
object.
Furthermore, even if that object is added to MCG, since it is a non-point
feature, MCG will not be able to use (cluster) it and it will not assign a
`__parent` property to it.

Why not using the callback of `zoomToShowLayer` to implement your
conversion when triggering that method?
That way you would ensure the marker is untouched until MCG no longer needs
it.
You would need to temporarily remove your listener from `zoomend` however.

We could still add a check on the existence of the `__parent` property,
though.
Better (but more complicated), we might need to assume that markers can be
removed in the middle of an animation (as seems to be your case).
I think the places that would be affected are `zoomToShowLayer` and the
spiderfication animations.

Hope this helps.

**Comment by mfc-julius** [comment]
Thanks for your ideas.

For now I will check myself for `__parent` before calling a method `zoomToShowLayer`. This should be the same as checking it inside the method, right? I will let you know if I'm still getting notifications after the change.

**Comment by danzel** [comment]
Guessing that fixed it for you?

**Comment by mfc-julius** [comment]
This did the trick, yes.
