### ISSUE TITLE
RefreshClusters VS singleMarkerMode: true

### ISSUE THREAD

**Issue by czb** [Leaflet/Leaflet.markercluster#581]
When using `singleMarkerMode: true`, the `refreshClusters` function should also run `iconCreateFunction` for all the end markers, not only cluster markers.

As it is now the cluster markers are updated but normal markers are not updated.

**Comment by ghybs** [comment]
Hi,

Good point.

We could add this functionality, or we could take the opportunity to re-visit this option `singleMarkerMode` to have real clusters containing the single markers, so that the behaviour is more consistent (see for example issue #391).

I guess the less effort rule will guide us towards the first option...
Any thoughts?

**Comment by czb** [comment]
Well, I do not know leaflet that much but to me it seems strange that you cannot use singleMarkerMode with disableClusteringAtZoom. Personally I would like to disable mark clusters on maximum zoom - I do not like spidering functionality.

What I try to achieve is to have fully dynamic styling of markers and marker clusters.

Let say that you mark bridges on a map. Each bridge has bad or good state (or yet another state). Each state of the bridge has a particular styling (bad state == red colour, good state == green colour). The mark clusters should be styled according to the worst state of bridges inside that cluster. State of the bridges can change at any time and should be immediately reflected in the map. How would you solve such particular case? I use singleMarkerMode and style both markers and marker clusters according to the bridge states.

**Comment by ghybs** [comment]
The "incompatibility" between `singleMarkerMode` and `disableClusteringAtZoom` is purely due to how these options are implemented, and is in fact just a visual artefact. In the case of `singleMarkerMode`, it appears that the "trick" to simply override the single marker icon was chosen on purpose (#42).

It is understandable to do it that way, and it sounds to fit for your use case as well: it conveniently avoids having to style your individual markers, while using the exact same `iconCreateFunction` to get similar style as clusters. E.g. you have a 1 bridge picture when single, and "stacked bridgeS" picture when clustered.

If using `singleMarkerMode` as it is now fits your need, the `disableClusteringAtZoom` is actually compatible: it prevents several markers from merging together past that zoom level, even if their style still **looks like**  single child clusters. Hence you no longer need spiderfication.

If on the contrary your individual markers needed differentiated styling (shape of the bridge let's say), then you would prefer normal mode, which is already covered by `refreshClusters` as it is today. With that mode, you would have to change the marker icon yourself to reflect your change of state, before calling the method to propagate the change to clusters.

So if my understanding is correct, there is no strong need for real clusters containing single markers, and the trick to style the markers with the same `iconCreateFunction` covers more use cases.
In that case, the `refreshClusters` method should definitely also re-draw the individual markers.

Is that what you mean?

I think the situation would be more clear if the option `singleMarkerMode` had been called with something like "markersIconOverride" or "restyleMarkersLikeClusters". The current name make us believe that it creates clusters even for a single marker (which was the original intention according to #42), whereas it actually just replaces the markers icon. The README looks to have a good [description of this](https://github.com/Leaflet/Leaflet.markercluster#all-options), but the option name is still misleading. Unfortunately once an API is released, it is almost impossible to change it except through a major revision.

Does that make sense?

**Comment by czb** [comment]
Hi,

thanks for the explanation. I have just tested you latest commit and it works perfectly! Thanks a lot for your help.

**Comment by ghybs** [comment]
Hi,

I am glad it solved your issue.
I must admit I totally missed that use case, thank you for reporting it.

**Comment by danzel** [comment]
Completed by @ghybs in #583
