### ISSUE TITLE
spiderLegPolylineOptions not working

### ISSUE THREAD

**Issue by YiuriV** [Leaflet/Leaflet.markercluster#593]
Hi, 

which version of the markercluster should I download to make the spiderLegPolylineOptions work? Right now I have taken the master-branch as that one is up to date. I've seen a hotfix for this problem, but that tag was dated a while back.

**Comment by ghybs** [comment]
Hi,

You are out of luck, only the source code in master branch includes the `spiderLegPolylineOptions` option. But the "dist" file has not been updated since that option was introduced. Similar issue as #592.

You could either re-build the master branch to get a new dist version from the source code, which includes that option. Or retrieve it from someone else's site. E.g. you can find one [here](http://ghybs.github.io/Leaflet.MarkerClusterGroup.Auto/examples/leaflet.markercluster-src.js). Note that this is for Leaflet 0.7.x.

Hope this helps.

**Comment by danzel** [comment]
I just posted some details in #592 related to this.
