### ISSUE TITLE
Possible to manually set the lat/long position a cluster marker?

### ISSUE THREAD

**Issue by cmalven** [Leaflet/Leaflet.markercluster#594]
Is there any way to manually set the position of a marker cluster instead of it automatically being determined based on it's children?

The use case is that I want to have a cluster for all of the properties in each country, but have the cluster marker centered in the country (which won't be the case if all of the properties are in the southwest part of the country).

**Comment by ghybs** [comment]
Hi,

There is currently no offered API to do so, but it is do-able if you are ready to fiddle with MCG internal variables.

I am not sure this could be made as a public API (but this involves just myself, I am not the owner of this plugin), because it would be unclear (in the general usage) at which point the cluster needs to use a manually specified position, rather than the average of positions of all contained markers.

E.g. in the case you describe, you would see one or several clusters in the southwest part of a country, and at a given zoom level, all of a sudden they would be placed at the country center. That could confuse users if that center is not in the current view. Furthermore, the cluster would be outside of its "coverage", which looks more like the map is broken rather than you intentionally placed the cluster at a conventional position, independently from its actual child markers. 

Nevertheless, in the case you want to implement it yourself, you could have a look at the source code of this demo: http://ghybs.github.io/Leaflet.markercluster/hierarchical-tree-of-groups/ (look for `_setSingletonLatLng` function).

Hope this helps.

**Comment by cmalven** [comment]
Sure, makes sense. I wasn't necessarily looking for a pubic API for doing this so much as a workaround that would accomplish the same thing (such as manually setting the marker position as a part of a click callback). It's clearly not something that the average developer would need to do. If there's no way to accomplish this outside of modifying the core, I think we can consider this closed.

**Comment by ghybs** [comment]
Actually I should probably have started by saying that the usual workaround for your use case is simply to hide the MCG at a certain zoom level and below, and to replace it by a single marker at your desired position. See for example the first example of #521.
