### ISSUE TITLE
Clusterclick returns wrong coordinates

### ISSUE THREAD

**Issue by vbernabe** [Leaflet/Leaflet.markercluster#595]
Hi,

I'm trying to get the coordinates of a cluster when clicked but it's giving me slightly different result.

  markers.addLayer(new L.Marker([1.3488888888888888, 103.76305555555555]));
  markers.addLayer(new L.Marker([1.3488888888888888, 103.76305555555555]));
  markers.addLayer(new L.Marker([1.3488888888888888, 103.76305555555555]));
  markers.addLayer(new L.Marker([1.3488888888888888, 103.76305555555555]));
  markers.addLayer(new L.Marker([1.3488888888888888, 103.76305555555555]));
  markers.addLayer(new L.Marker([1.3488888888888888, 103.76305555555555]));

On clusterclick this will return 1.3488888888888886 103.76305555555554 long lat coordinates

But If I only have 5 markers with same coordinates it will return the correct result (i.e. 1.3488888888888888 103.76305555555555)

Here's my sample code http://jsfiddle.net/e3fdggpr/1/

Any ideas?

Thanks!

**Comment by IvanSanchez** [comment]
You're hitting a hiccup of floating point arithmetic in the least significant bit due to rounding errors (sum floats N times then divide them by N will cause a loss of precision). If that's an issue for you, I suggest you:

* Read up on floating point arithmetic, starting [here](https://en.wikipedia.org/wiki/Floating_point)
* Use [`L.LatLng.equals`](http://leafletjs.com/reference.html#latlng-equals) to compare latlng objects.

Short of switching all the code to emulate 64-bit floats or arbitrary-precision arithmetic (which BTW would reduce performance by orders of magnitude), there's nothing that can be done.

Also keep in mind that the error margin we're talking about is in **nanometers**. If you need nanometer precision, use a different CRS.
