### ISSUE TITLE
Exclude marker with active popup from cluster

### ISSUE THREAD

**Issue by medihack** [Leaflet/Leaflet.markercluster#596]
I have some markers with bound popups inside a cluster. I want to exclude a marker with an opened popup from the cluster when zooming out.
So I thought about removing it from the cluster (`cluster.removeLayer(marker)`) and adding it to the map directly (`map.addLayer(marker)`). Unfortunately removing the marker from the cluster does close the popup. I don't see a way to prevent this. I tried calling `event.originalEvent.preventDefault()` in the click event handler, but it doesn't work.
Do you know a way to accomplish that? Maybe in such dynamic cases something like `cluster.excludes(markers)` would help (with markers a list of markers or null (the default)).

**Comment by ghybs** [comment]
Hi,

When you remove your marker from MCG, it is removed from map (if it was not clustered, which is your case since you were able to click on it and open the popup).

Adding a way to "exclude" a marker from MCG but leaving it on map could be done, but it would probably require quite some amount of code re-factoring.

There should be 2 simple workarounds for your need:
- Either remove from MCG, add to map and re-open the popup. The latter may flicker a little (but it may not be noticeable, to be tested).
- Or do the reverse: add an on "click" listener on your marker, which removes it from MCG, adds it to the map, binds the popup and opens it.

**Comment by medihack** [comment]
Yes, sure ... thought of this too. I guess the second option is the better one (more clean as I also do stuff on popupclose). But maybe an `excludes` function would be a nice to have feature in a future version.

**Comment by danzel** [comment]
Yeah, probably not going to happen sorry.
