### ISSUE TITLE
Spiderfying doesn't work with Awesome Markers plugin

### ISSUE THREAD

**Issue by hokascha** [Leaflet/Leaflet.markercluster#598]
When using Awesome Markers https://github.com/lvoogdt/Leaflet.awesome-markers to create markers, the spiderfying effect doesn't work. Markers are just faded in&out but not moved.
```javascript
var markers = new L.MarkerClusterGroup();
$.ajax({
			    type: "GET",
			    url: "/?p=map&json=1",
			    dataType: 'json',
			    success: function (response) {
			        geojson = L.geoJson(response, {
			        	pointToLayer: function (feature, latlng) {
			                   return L.marker(latlng,{icon:     L.AwesomeMarkers.icon({
				                                                             icon: 'circle-o',
                     			                                                     markerColor: 'blue',
				                                                             prefix: 'fa'
				                                                             })
                                                      });
			          });
			        markers.addLayer(geojson);
			        map.addLayer(markers);
			    }
			});
```

**Comment by ghybs** [comment]
Hi,

If you pay close attention, you will notice that Awesome Markers do not animate either when splitting from / merging into clusters. This is simply because Awesome Markers plugin replaced the [`leaflet-marker-icon`](https://github.com/Leaflet/Leaflet/blob/stable/src/layer/marker/Icon.js#L69) class by [`awesome-marker-icon`](https://github.com/lvoogdt/Leaflet.awesome-markers/blob/2.0/develop/dist/leaflet.awesome-markers.js#L97) (same with `-shadow`).

Same issue with [Extra Markers](https://github.com/coryasilva/Leaflet.ExtraMarkers) plugin (which I would recommend over Awesome Markers since it is more recent and offers more options by the way).

You have 2 simple solutions:

- Either add `.leaflet-cluster-anim .awesome-marker-icon` and `.leaflet-cluster-anim .awesome-marker-shadow` selectors into [MarkerCluster.css](https://github.com/Leaflet/Leaflet.markercluster/blob/master/dist/MarkerCluster.css#L1).
- Or add `"leaflet-marker-" + name` into [leaflet.awesome-markers.js _setIconStyles method](https://github.com/lvoogdt/Leaflet.awesome-markers/blob/2.0/develop/dist/leaflet.awesome-markers.js#L97).

Let me know if this does not work for you.

**Comment by hokascha** [comment]
Thanks, works!

**Comment by ghybs** [comment]
Hi,

Just to let you know that [Leaflet.ExtraMarkers](https://github.com/coryasilva/Leaflet.ExtraMarkers) has just been corrected to include the 2 missing classes.

Awesome-Markers is no longer maintained by its author unfortunately.
