### ISSUE TITLE
Feature Request - Ability to cluster polygons

### ISSUE THREAD

**Issue by bunnis** [Leaflet/Leaflet.markercluster#612]
Hi
I would like to cluster other type of data, like polygons. Basically doing the same the plugin does but instead of showing markers, showing polygons at the end of the zoom.

**Comment by ghybs** [comment]
Hi,

You might be interested in [Leaflet.Deflate plugin](https://github.com/oliverroick/Leaflet.Deflate), but be careful when removing the marker (see #580).

Another possibility would be to "add" methods `getLatLng` and `setLatLng` to your polygons, so that MCG can handle them like points. But the result might not be like what you expect, as the polygons would cluster based on the position of their center (or whatever position you return through `getLatLng`), not on their shape.

Demo: http://jsfiddle.net/ve2huzxw/80/

**Comment by bunnis** [comment]
How can one define a max cluster zoom level on the demo you did? BTW great demo, exactly what I was looking for

**Comment by ghybs** [comment]
Have you tried [option `disableClusteringAtZoom`](https://github.com/Leaflet/Leaflet.markercluster#other-options)?

Updated demo: http://jsfiddle.net/ve2huzxw/82/

**Comment by bunnis** [comment]
worked like a charm! thank you very much!

**Comment by maxwell-oroark** [comment]
By chance, have you stress tested this solution with hundreds of thousands of geojson polygons?  

If so, how did it perform at this scale?  Thanks!

**Comment by ghybs** [comment]
Hi,

Test for yourself: https://jsfiddle.net/ve2huzxw/307/

Computation of clusters is rather long for 500k features (!!!), so you should probably consider pre-computation if your features do not change too much over time.

But then, navigation is rather smooth I find, at least on my machine.

**Comment by gregholst** [comment]
@ghybs unfortunately your jsfiddles don't seem to work anymore

**Comment by bunnis** [comment]
jsfiddle looks down right now https://www.isitdownrightnow.com/jsfiddle.com.html

**Comment by fasilofficial** [comment]
Hello, 

Instead of regular shapes like circles and rectangles, can this be used for an GeoJSON polygon?

**Comment by charlieforward9** [comment]
It would be nice to have this added as an option within this plugin rather than a custom extension of the plugin! If someone is interested in re-vitalizing the [associated react-leaflet plugin](https://github.com/yuzhva/react-leaflet-markercluster) with this functionality. Please reach out! I'd love to contribute to open source and use this functionality.

**Comment by charlieforward9** [comment]
Wow, almost a year after I finally got around to this again. Given my use case, I created a minimal sample: https://github.com/yuzhva/react-leaflet-markercluster/pull/211 inspired by the many jsfiddle's in here 

It would still be nice to see this somehow embedded into the root plugin, but for now, it can be used with pure-JS using the jsfiddle samples and react using my sample.
