### ISSUE TITLE
Error when removing markercluster from layer control

### ISSUE THREAD

**Issue by davidlukerice** [Leaflet/Leaflet.markercluster#616]
I need to be able to add or remove a marker cluster from the map and layers control depending on what base layer is selected. Whenever I change base layers, however, a `Uncaught TypeError: Cannot read property 'layerId' of undefined` gets thrown when it removes the cluster layer from the layers control. This causes bugs when transitioning back to the original base layer.
http://jsfiddle.net/davidlukerice/rre49s1x/2/

**Comment by ghybs** [comment]
Hi,

It seems this is not related to MCG but rather to how the Layers Control works.
For instance, replacing the MCG in your jsfiddle by a simple Layer Group shows the exact same issue: http://jsfiddle.net/rre49s1x/4/

I think this is due to trying to remove a layer from the Layers Control when the `"baselayerchange"` event is fired, whereas the Layers Control will still try to iterate through its previous list of layers.

Using a simple timeout lets the Layers Control complete its iterations before actually removing the overlay: http://jsfiddle.net/rre49s1x/5/

Cheers

**Comment by danzel** [comment]
Try this with a recent version of leaflet / leaflet.markercluster.
You are using leaflet 0.6.2.

**Comment by davidlukerice** [comment]
Had forked off another jsfiddle and hadn't checked version numbers. Here's an updated one:
http://jsfiddle.net/davidlukerice/rre49s1x/7/
Also moved the setTimeout around the entire update function, since there was still the issue of having to click on the previous layer twice before it fully switched over correctly.
Everything seems to work now with those changes. Thanks for the help!
