### ISSUE TITLE
Error when adding markers

### ISSUE THREAD

**Issue by masterflank** [Leaflet/Leaflet.markercluster#635]
When our markers have got an updated position we remove them from the cluster group and adds them again in order to "recluster". A few times we have got an error in _addLayer function saying

`TypeError: Cannot read property '_zoom' of undefined`

The error ocurred in version v0.4.0-hotfix.1 together with leaflet 0.7.3, Chrome browser. I haven't figured out exactly what the preconditions are in order to reproduce it in a fiddle, but I tracked it down to the following piece of code in function _addLayer of L.MarkerClusterGroup

```
if (closest) {
  var parent = closest.__parent;
  if (parent) {
    this._removeLayer(closest, false);
  }

  //Create new cluster with these 2 in it

  var newCluster = new L.MarkerCluster(this, zoom, closest, layer);
  gridClusters[zoom].addObject(newCluster, this._map.project(newCluster._cLatLng, zoom));
  closest.__parent = newCluster;
  layer.__parent = newCluster;

  //First create any new intermediate parent clusters that don't exist
  var lastParent = newCluster;
  for (z = zoom - 1; z > parent._zoom; z--) {
    lastParent = new L.MarkerCluster(this, z, lastParent);
    gridClusters[z].addObject(lastParent, this._map.project(closest.getLatLng(), z));
  }
```

If closest.__parent is undefined then parent will be undefined. When parent._zoom is used in for loop we get the error.

**Comment by danzel** [comment]
I think you are trying to remove a marker that isn't in the cluster or something like that maybe.

If you have a way of reproducing this easily and it is a markercluster issue we could try fix it.

**Comment by CatchSandeepVaid** [comment]
I am facing exactly the same problem. Basically i want to move markers and i am using markercluster library as well. 
1)  It seems markercluster doesnt support this feature out of box. See [https://github.com/Leaflet/Leaflet.markercluster/issues/105] and danzel commented as "_So you are moving markers within a marker cluster? That isn't supported.It is supported in the leaflet-master branch using the master version of leaflet"_

2) I thought if i cant move marker, i can use remove+add marker combination to have the same effect as move but again it gives error:

`TypeError: Cannot read property '_zoom' of undefined`

**Comment by ghybs** [comment]
Hi,

Really hard to tell what could be the reason for this issue, without a proper case reproduction…
Please could you at least confirm the Leaflet and MCG versions you are using?

In theory, `parent = closest.__parent` should always be defined (at least `parent` would be `this._topClusterLevel`), so we should even be able to get rid of the [`if` condition](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L929)…

But it looks like in some weird situations, the `__parent` property is lost.
Now we need to find out when this situation happens?

**Comment by ghybs** [comment]
I think I get it.

If your marker changed position (coordinates) **before** you remove it, MCG may be in trouble properly [eliminating its references](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L650) from its internal `_gridUnclustered` Distance Grid: it reads its (new) coordinates, derives its associated grid (new) index and may not find it there, stopping reference elimination.

Then you are left with a "ghost" in the Distance Grid, even though it is supposed to be removed. In particular, `removeLayer()` [deleted its `__parent` property](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L721).

Then later when you add another marker (or even the same one!), `addLayer` may find this ghost and try to cluster with it, but it will fail reading properties of the ghost's `__parent`.

Now, in MCG version v1.0.0-beta.2.0 and above (actually since Jan 2014 in commit https://github.com/Leaflet/Leaflet.markercluster/commit/27827b5d63317aa7fb6800500984857ca24f16fa of MCG branch compatible with Leaflet 1.0), MCG adds `"move"` event listener on all markers and automatically handles the `removeLayer` + `addLayer` process for you, properly [using the old position](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L658) to avoid creating that "ghost" in Distance Grid.

Therefore, if you are using Leaflet 0.7 with MCG 0.5, you could try removing your marker from MCG **before** actually moving it, if your application can handle the process that way.

But if you are already using Leaflet 1.0 with MCG 1.0 and the automatic clusters update does not happen, please try to bring more details and to provide a case reproduction so we can dig further.

**Comment by CatchSandeepVaid** [comment]
Actually i am using angular-leaflet-directive [](https://github.com/tombatossals/angular-leaflet-directive) (v0.10.0) which internally uses  leaflet(0.7.x) and leaflet.markercluster (* - I think, in bower it means latest stable version which is at present 0.5).

Its already an open issue in angular-leaflet-directive : See [](https://github.com/tombatossals/angular-leaflet-directive/issues/690), [](https://github.com/tombatossals/angular-leaflet-directive/issues/685)


In one of their examples([http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/layers/overlays-markercluster-example]), they have mentioned 
"The MarkerCluster, at this moment, does not support the location change of the markers and they have to be  removed and added again to the cluster. So, as we remove & add markers when the model is changed.

So does this mean that its not an issue with markercluster library but its an issue in angular-leaflet-directive library ?

**Comment by ghybs** [comment]
Hi,

Indeed it looks so to me, since it all depends on how the application (or in your case angular-leaflet-directive) handles marker movements.

Besides, the latest MCG version (1.0) already handles it automatically, and this feature depends on Leaflet 1.0, so there is unfortunately almost no chance that it is back ported to version 0.5.0...

**Comment by sergeyba-asg** [comment]
I can be wrong but looks here is an error in MarkerClusterGroup.js

if (layer.__parent) {
			while (visibleLayer.__parent._zoom >= currentZoom) {
				visibleLayer = visibleLayer.__parent;
			}
}

here is a check against layer but in code logic with visibleLayer.

**Comment by mapkyca** [comment]
I'm getting the same issue... A markerClusterGroup was created, and a function adds points to it from an ajax call. Most points are added, but at some point it seems like something breaks inside the markerClusterGroup. These are all new points, so I'm not sure how I could be redefining or moving them, certainly I'm not trying to do it deliberately...

**Comment by jeancaffou** [comment]
I am able to inconsistently reproduce this when switching between two layer groups: one for all markers, and the other one is a MarkerCluster layer.

As far as I know there is still no built in option to switch between disabling/enabling clustering on a MarkerClusterGroup.

This happens randomly when calling map.addLayer(markerClusterGroup)  and map.addLayer(allMarkersGroup) and vice-versa while zooming in and out of the map (sometimes not even zooming).

Marker locatios are updated (possibly causing this bug - mentioned in #105 ). I don't think this happens if marker locations are not updated.

I am reusing marker instances between the two layer groups, so if I call addLayer(cluster) before removeLayer(allMarkers), then markers not in the cluster disappear from the map.

I will try to debug this further and maybe clone instances for the two layer groups as a workaround.

**Comment by sergeyba-asg** [comment]
sergey.bartoshik@asg.com is no longer a valid e-mail address.  Please contact Bill Dulyk at bill.dulyk@asg.com with any questions, comments, or concerns.

Diese sergey.bartoshik@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Bill Dulyk an folgende Email-Adresse bill.dulyk@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette sergey.bartoshik@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Bill Dulyk a l'adresse de courriel suivante bill.dulyk@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: bounces+848413-9cf6-sergey.bartoshik=asg.com@sgmail.github.com
Sent: Sunday, January 8 2017 10:52 PM
To: Leaflet.markercluster@noreply.github.com
CC: Sergey.Bartoshik@asg.com, comment@noreply.github.com
Subject: [BULK] Re: [Leaflet/Leaflet.markercluster] Error when adding markers (#635)


I am able to inconsistently reproduce this when switching between two layer groups: one for all markers, and the other one is a MarkerCluster layer.

As far as I know there is still no built in option to switch between disabling/enabling clustering on a MarkerClusterGroup.

This happens randomly when calling map.addLayer(markerClusterGroup) and map.addLayer(allMarkersGroup) and vice-versa while zooming in and out of the map (sometimes not even zooming).

Marker locatios are updated (possibly causing this bug - mentioned in #105<https://github.com/Leaflet/Leaflet.markercluster/issues/105> ). I don't think this happens if marker locations are not updated.

I am reusing marker instances between the two layer groups, so if I call addLayer(cluster) before removeLayer(allMarkers), then markers not in the cluster disappear from the map.

I will try to debug this further and maybe clone instances for the two layer groups as a workaround.

**Comment by jeancaffou** [comment]
Setting up clone markers for the two layer groups doesn't seem to fix the problem.
Now I see that it crashes when I **modify the cluster layer group when it is not added to the map** (example: changing marker positions), and when I map.addLayer(clusterGroup) it crashes:

```
leaflet.markercluster.js:947 Uncaught TypeError: Cannot read property '_zoom' of undefined
    at NewClass._addLayer (leaflet.markercluster.js:947)
    at NewClass.<anonymous> (leaflet.markercluster.js:238)
    at NewClass.addLayers (leaflet.markercluster.js:269)
    at NewClass.onAdd (leaflet.markercluster.js:597)
    at NewClass._layerAdd (leaflet.js:3960)
    at NewClass.whenReady (leaflet.js:3602)
    at NewClass.addLayer (leaflet.js:4018)
    at HTMLAnchorElement.toggleCluster (ui.js:811)
```

**Comment by sergeyba-asg** [comment]
Sergey.Bartoshik@asg.com is no longer a valid e-mail address.  Please contact Bill Dulyk at bill.dulyk@asg.com with any questions, comments, or concerns.

Diese Sergey.Bartoshik@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Bill Dulyk an folgende Email-Adresse bill.dulyk@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette Sergey.Bartoshik@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Bill Dulyk a l'adresse de courriel suivante bill.dulyk@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Montag, Januar 9 2017 12:25
To: Leaflet.markercluster@noreply.github.com
CC: Sergey.Bartoshik@asg.com, comment@noreply.github.com
Subject: Re: [Leaflet/Leaflet.markercluster] Error when adding markers (#635)


Setting up clone markers for the two layer groups doesn't seem to fix the problem.
Now I see that it crashes when I modify the cluster layer group when it is not added to the map (example: changing marker positions), and when I map.addLayer(clusterGroup) it crashes:

leaflet.markercluster.js:947 Uncaught TypeError: Cannot read property '_zoom' of undefined
    at NewClass._addLayer (leaflet.markercluster.js:947)
    at NewClass.<anonymous> (leaflet.markercluster.js:238)
    at NewClass.addLayers (leaflet.markercluster.js:269)
    at NewClass.onAdd (leaflet.markercluster.js:597)
    at NewClass._layerAdd (leaflet.js:3960)
    at NewClass.whenReady (leaflet.js:3602)
    at NewClass.addLayer (leaflet.js:4018)
    at HTMLAnchorElement.toggleCluster (ui.js:811)

**Comment by ghybs** [comment]
@jeancaffou if you change a marker position while the MCG is off map, the automatic management will probably not work (no emitted events).

You should probably simply remove the marker from your MCG, change its position, then add it back to MCG.

If this does not solve your issue, please provide a [Leaflet playgroud](http://playground-leaflet.rhcloud.com/) / Plunker / JSFiddle that reproduces the problem, and consider asking for help on Stack Overflow.

Note: as for showing clustered and unclustered markers, you might be interested in [Leaflet.MarkerCluster.Freezable](https://github.com/ghybs/Leaflet.MarkerCluster.Freezable) sub-plugin.

**Comment by sergeyba-asg** [comment]
Sergey.Bartoshik@asg.com is no longer a valid e-mail address.  Please contact Bill Dulyk at bill.dulyk@asg.com with any questions, comments, or concerns.

Diese Sergey.Bartoshik@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Bill Dulyk an folgende Email-Adresse bill.dulyk@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette Sergey.Bartoshik@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Bill Dulyk a l'adresse de courriel suivante bill.dulyk@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Montag, Januar 9 2017 5:58
To: Leaflet.markercluster@noreply.github.com
CC: Sergey.Bartoshik@asg.com, comment@noreply.github.com
Subject: Re: [Leaflet/Leaflet.markercluster] Error when adding markers (#635)


@jeancaffou<https://github.com/jeancaffou> if you change a marker position while the MCG is off map, the automatic management will probably not work (no emitted events).

You should probably simply remove the marker from your MCG, change its position, then add it back to MCG.

If this does not solve your issue, please provide a Leaflet playgroud<http://playground-leaflet.rhcloud.com/> / Plunker / JSFiddle that reproduces the problem, and consider asking for help on Stack Overflow.

Note: as for showing clustered and unclustered markers, you might be interested in Leaflet.MarkerCluster.Freezable<https://github.com/ghybs/Leaflet.MarkerCluster.Freezable> sub-plugin.

**Comment by jeancaffou** [comment]
> Note: as for showing clustered and unclustered markers, you might be interested in [Leaflet.MarkerCluster.Freezable](https://github.com/ghybs/Leaflet.MarkerCluster.Freezable) sub-plugin.

Thanks. This solution is much cleaner and currently surviving my test cases.

**Comment by sergeyba-asg** [comment]
Sergey.Bartoshik@asg.com is no longer a valid e-mail address.  Please contact Bill Dulyk at bill.dulyk@asg.com with any questions, comments, or concerns.

Diese Sergey.Bartoshik@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Bill Dulyk an folgende Email-Adresse bill.dulyk@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette Sergey.Bartoshik@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Bill Dulyk a l'adresse de courriel suivante bill.dulyk@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Monday, January 9 2017 9:30 AM
To: Leaflet.markercluster@noreply.github.com
CC: Sergey.Bartoshik@asg.com, comment@noreply.github.com
Subject: Re: [Leaflet/Leaflet.markercluster] Error when adding markers (#635)


Note: as for showing clustered and unclustered markers, you might be interested in Leaflet.MarkerCluster.Freezable<https://github.com/ghybs/Leaflet.MarkerCluster.Freezable> sub-plugin.

Thanks. This solution is much cleaner and currently surviving my test cases.

**Comment by danzel** [comment]
Moving markers using setLatLng or dragging should be all working on 1.0.1

**Comment by sergeyba-asg** [comment]
Sergey.Bartoshik@asg.com is no longer a valid e-mail address.  Please contact Bill Dulyk at bill.dulyk@asg.com with any questions, comments, or concerns.

Diese Sergey.Bartoshik@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Bill Dulyk an folgende Email-Adresse bill.dulyk@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette Sergey.Bartoshik@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Bill Dulyk a l'adresse de courriel suivante bill.dulyk@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: noreply@github.com
Sent: Mittwoch, Januar 25 2017 8:54
To: Leaflet.markercluster@noreply.github.com
CC: Sergey.Bartoshik@asg.com, comment@noreply.github.com
Subject: Re: [Leaflet/Leaflet.markercluster] Error when adding markers (#635)


Closed #635<https://github.com/Leaflet/Leaflet.markercluster/issues/635>.

**Comment by sergeyba-asg** [comment]
sergey.bartoshik@asg.com is no longer a valid e-mail address.  Please contact Bill Dulyk at bill.dulyk@asg.com with any questions, comments, or concerns.

Diese sergey.bartoshik@asg.com ist keine gultige Email-Adresse mehr. Bitte setzen Sie sich mit Bill Dulyk an folgende Email-Adresse bill.dulyk@asg.com in Verbindung, falls Sie etwaige Fragen, Kommentare oder Bedenken diesbezuglich haben.

Cette sergey.bartoshik@asg.com n'est plus une adresse de courriel valable. Veuillez contacter Bill Dulyk a l'adresse de courriel suivante bill.dulyk@asg.com si vous avez des questions, des commentaires ou des preoccupations quelconques.

From: bounces+848413-9cf6-sergey.bartoshik=asg.com@sgmail.github.com
Sent: Mittwoch, Januar 25 2017 8:54
To: Leaflet.markercluster@noreply.github.com
CC: Sergey.Bartoshik@asg.com, comment@noreply.github.com
Subject: [BULK] Re: [Leaflet/Leaflet.markercluster] Error when adding markers (#635)


Moving markers using setLatLng or dragging should be all working on 1.0.1

**Comment by thernoff** [comment]
Maybe my decision will help someone:
1) I create my marker based on L. Marker, consisting of a normal marker and a circle
<pre><code>
var RangeMarker = L.Marker.extend ({
  initialize: function (latlng, options) {
    L.setOptions (this, options);
    this._latlng = L.latLng (latlng);
    if (Math.abs (this.options.precision) && this.options.showRange) {
      this._circle = L.circle (this._latlng, {
          radius: Math.abs (this.options.precision),
            weight: 1
          });
    }
  },
  // .. the rest of the code
});
</pre></code>
2) In it, I override the setLatLng method:
<pre><code>
setLatLng: function (latlng) {
  var latLng = L.latLng(latlng);
  this._latlng = latLng;

  L.Marker.prototype.setLatLng.call(this, latLng);
  if (this._circle) {
	this._circle.setLatLng(this._latlng);
  }
  return this;
}
</pre></code>
3) Calling this method (that is, when I update the coordinates of the marker) an error occurs:
<pre><code>
TypeError: Cannot read property '_zoom' of undefined
    at e._addLayer (MarkerClusterGroup.js: 999)
    at e.addLayer (MarkerClusterGroup.js: 111)
    at e._moveChild (MarkerClusterGroup.js: 707)
    at e._childMarkerMoved (MarkerClusterGroup.js: 694)
    at e.fire (leaflet.js: 5)
    at e.setLatLng (leaflet.js: 5)
    at e.setLatLng (devices-leaflet.js: 587)
    at e.updateMarker (devices-leaflet.js: 617)
    at devices-leaflet.js: 516
    at Array.forEach (<anonymous>)
</pre></code>
4) As I understand it, it occurred because of the line: this._latlng = latLng.
In leaflet.markercluster-src.js there is a _moveChild method that also has something like this:
<pre><code>
_moveChild: function (layer, from, to) {
  layer._latlng = from;
  this.removeLayer(layer);

  layer._latlng = to;
  this.addLayer(layer);
}
</pre></code>
5) The error disappeared after I removed this._latlng = latLng from my code.
