### ISSUE TITLE
Large datasets causing issues

### ISSUE THREAD

**Issue by jared-clarifai** [Leaflet/Leaflet.markercluster#695]
Hey guys -

1) I'm using this to show all of my company's API calls from the past 30 minutes and that typically ranges in the 150,000 - 250,000 area. Seems that it takes ~30 seconds to load a map of this magnitude - would it help if I split the items into multiple JS files? (Right now I'm storing everything in one file). 

2) When I click on a node with 3,000 or more data points (same exact lat/long) the browser freezes a bit. Wondering if I should just set SpiderfyOnMaxZoom to false to disable that - though I'm also curious if there's a way to do that and still show one popup on a click to summarize all 3,000 points. Is that possible?

**Comment by ghybs** [comment]
Hi,

Feel free to ask for help on [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet), where you would receive a larger audience that can provide you with support on your project.

1) If your data file must be retrieved from network, there is a chance most of the time is spent in downloading. Splitting in multiple files might help for that case (as you could download them by 2). Otherwise, it is probably pointless. Have a look at [`chunkLoading`](https://github.com/Leaflet/Leaflet.markercluster#chunked-addlayers-options) option to retrieve some usability, in exchange of a slightly longer loading time.

2) Browser freeze is due to trying to show 3k markers on the view port. Whether they are spiderfied or not would not change a lot. As for your request, you could implement your own [`"clusterclick"`](https://github.com/Leaflet/Leaflet.markercluster#events) event listener to show your popup rather than the 3k markers.

In the situation you describe, you might be interested in using a heat map rather than clusters.

**Comment by danzel** [comment]
Do you need to show individual API calls, or could you aggregate them a bit on the server side?
Those are big numbers no matter what you do with them.

**Comment by jared-clarifai** [comment]
Thanks for the feedback guys. I'll play around with it a bit and see what I can come up with

**Comment by TheMangoTrain** [comment]
Anecdote: I also have a data-heavy app (e.g. trying to have 40,000 markers, with clustering, at once) and also found 3000 to be where you start feeling a noticeable reduction in performance. I'm making adjustments to UX/UI by adding paged search results, restrictions on zooming and filters, "search this area" type of features, etc.
