### ISSUE TITLE
Canvas CircleMarker flicker on cluster animation

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet.markercluster#727]
Originally https://github.com/Leaflet/Leaflet/issues/5011, reported by @stefanhagiu

When:
* There is a markercluster
* Which has its `animated` option is set to true
* And has `L.CircleMarker`s instead of `L.Marker`s
* And the markers are rendered in a `L.Canvas`

then, the `CircleMarker`s will flicker during a zoom animation, as the cluster marker is destroyed/created and the individual markers are destroyed/created.

Reproducible test case:

*    using leaflet + marker cluster + svg [ works as expected ]: https://codepen.io/anon/pen/YGLbGq?editors=1010
*    using leaflet + marker cluster + canvas [ fails to work ]: https://codepen.io/anon/pen/PGZONy?editors=1010
*    using leaflet + canvas [ no clustering works as expected]: https://codepen.io/anon/pen/wzjbgP?editors=1010

**Comment by stefanhagiu** [comment]
I've created a cleaner example where you can see the problem (the examples that i gave were full of stuff that are unnecessary in reproducing the problem e.g. projection change).

link to cleaner example: https://codepen.io/anon/pen/vXAqyZ?editors=0010
- to making work comment line 7 or on line 1 set  `preferCanvas:true` to `preferCanvas:false`

**Comment by ghybs** [comment]
Hi,

As pointed out by @IvanSanchez, this bug is caused by the removal and adding back of the `L.CircleMarker`'s.

Reproduced bug _without_ Leaflet.markercluster:
https://plnkr.co/edit/56Ko7i2JLr0tl5zo7m7F?p=preview
(this also shows that it looks to affect _all_ shapes, not only `L.CircleMarker`)

```javascript
var firstLayer = L.layerGroup().addTo(map),
    innerGroup = L.layerGroup().addTo(firstLayer);

map.on("zoomend", function () {
  firstLayer.removeLayer(innerGroup);
  console.log("innerGroup is removed");
  firstLayer.addLayer(innerGroup);
  console.log("innerGroup is added back");
});
```

(paths are added into `innerGroup`)

Really weird, as the shapes are cut by a central square, but it looks to have nothing to do with Grid Layer…

**Comment by ghybs** [comment]
Looks like it is caused by `L.Canvas` flag `layer._removed`
https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L95

It is set when layer is removed from canvas, but cleared only on deferred `_draw`.
Therefore when adding the layer to the canvas, it catches the flag and removes the layer from canvas just after having adding it…

Clearing that flag when calling `_initPath` looks to fix the issue.
https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L87

Fixed Plunker: https://plnkr.co/edit/jm1qNpdEpPJPDRdXk9ja?p=preview

**Comment by stefanhagiu** [comment]
OK, I've tested the fix on my project and it all works as expected 😀. Thanks a lot for solving this 👍

**Comment by ghybs** [comment]
Hi,

Fix is merged into `master`.

It should be shipped with next Leaflet release.

**Comment by IvanSanchez** [comment]
Fixed upstream in https://github.com/Leaflet/Leaflet/issues/5011
