### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getMinZoom' of null

### ISSUE THREAD

**Issue by arminus** [Leaflet/Leaflet.markercluster#758]
I just switched from 1.0.2 (I think) to 1.0.3, when zooming in and out of my map, I get this (during the 3rd or 4th zoom, not right away)

Uncaught TypeError: Cannot read property 'getMinZoom' of null
    at e._recursivelyRemoveChildrenFromMap (leaflet.markercluster-src.js:1712)
    at leaflet.markercluster-src.js:1349

That line changed from

`this._recursively(previousBounds, -1, zoomLevel - 1,`

to

`this._recursively(previousBounds, this._group._map.getMinZoom() - 1, zoomLevel - 1,`

Leaflet is either 1.0.2 or 1.0.3, browser is Chrome latest.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by arminus** [comment]
It's not that easy to extract that... here's a test page were I've just replaced the MarkerCluster version:

https://www.xctrails.org/map/map-test.html

The production version (with the older MarkerCluster version) is at https://www.xctrails.org/map/map.html

**Comment by danzel** [comment]
Might be a bug. I'm not going to debug your whole app to find out though, you are going to have to do some work to extract a failing case.
I guess you are adding/removing MarkerClusterGroups from the map? Maybe try start there.
 http://playground-leaflet.rhcloud.com/beg/1/edit?html,output is a starting project to make a test case from. Thanks!

**Comment by arminus** [comment]
I understand and I'll try, although I'm rather sure that this is not going to be easy.

On the other hand: what triggered the change in line 1712?

**Comment by danzel** [comment]
The change was to support negative minZoom

**Comment by hanzo2001** [comment]
I have just ran into this uncaught error myself. I also am having trouble trying to replicate(*) and extract the issue but my money is on some zoom process that happens right after clearing up the map.

(*) In my case I'm laying down between 50 and 250 markers in one fell swoop. All the markers are saved into a single cluster object. The amount depends on the distance to a latLng. On marker load, there is an automatic recalculation of the boundaries so It will auto-zoom in or out depending on whether there's more or less markers. Between each step there is a full cleanup of the map, which means that the marker cluster object is simply removed (alongside all of its contained markers). The issue has only shown up when the process causes a zoom out. I have been unsuccessful attempting to replicate this issue, it simply crops up a third of the time with parameters that are known to fail. Every time I hit a new scenario where it does it again I write down all the parameters and attempt to replicate it.

The only thing that seems constant is the fact that it happens when a larger set of markers is painted over the map which causes a zoom out (or just before the zoom), which should cause cluster-ification (of most markers and some cluster groups). I wish I could do more about this but I have no way of successfully sharing a problem scenario.

**Comment by LoicUV** [comment]
I have the same error, and i'm using react, react-leaflet, and react-leaflet-markercluster. Now I know you don't provide support for this setup, but It might help resolve this nonetheless.

Here's what happens when I zoom-out from a view with at least one cluster : 
- the zoom-out event calls the moveend event on the map
- I listen to the moveend to fetch my new markers position based on map bounds
- I replace the markers with the new ones (here happens the react stuff)
- error pops up, fails here `this._group._map.getMinZoom()` surely due to the fact that the `group` has been removed to create a new one with new markers in the meantime.

Now I don't know if adding a test to check that `group` isn't null before proceeding is the right way to go, or if there's any other proper solution.

**Comment by danzel** [comment]
Can you make an example on jsfiddle/codepen?
You should be able to replace your fetch with a setTimeout block.

Would like to fix but need a testcase! Thanks.

**Comment by LoicUV** [comment]
Here it is http://playground-leaflet.rhcloud.com/wexa/5/edit?html,output 🎉 
Changing the setTimeout duration to 300 removes the error

**Comment by ghybs** [comment]
Hi,

@LoicUV thanks a lot for the test case!

If 300ms is the cutoff for the bug to disappear, this very probably points out the [`_animationZoomOutSingle`](https://github.com/Leaflet/Leaflet.markercluster/blob/v1.0.3/src/MarkerClusterGroup.js#L1315) that uses the [`_enqueue`](https://github.com/Leaflet/Leaflet.markercluster/blob/v1.0.3/src/MarkerClusterGroup.js#L1030-L1036) method, which has a 300ms timeout.

We could probably improve through 2 approaches, that may be combined:
1. Cache the map `minZoom` when MCG is added to map. I do not think it can change dynamically. If it did change, MCG would be in trouble if it gets lower, because it would have to recompute its top level cluster…
2. Cancel the markers / clusters removal that had been enqueued if we realize we are no longer on map, since `this._featureGroup` is no longer on map anyway. But we may still have to restore opacities and latLng positions?

**Comment by danzel** [comment]
Have pushed up a fix that works for that test.

Please try this version in your app, there are possibly other places the error can occur:
https://gist.github.com/danzel/173297195f053e17a61117e90c64e469
If it still breaks somewhere, please paste the stacktrace.

**Comment by LoicUV** [comment]
Tested it in my app, the error doesn't appear anymore. Thanks 👍

**Comment by danzel** [comment]
Thanks, 1.0.4 released

**Comment by LoicUV** [comment]
Can you publish it to npm please ?

**Comment by danzel** [comment]
Woops! Doing it now...
