### ISSUE TITLE
minZoom / maxZoom show/hide markerCluster Group

### ISSUE THREAD

**Issue by larotech** [Leaflet/Leaflet.markercluster#782]
Hi,

I'm not sure if this is a bug or not implemented or just a misunderstanding but i'm trying to use minZoom and maxZoom in the Marker Cluster Group options to show the cluster of markers between a specific zoom range.

var myCluster =new L.MarkerClusterGroup({...., minZoom:1,maxZoom:10});
myCluster.addTo(map);

Zooming in passed 10 and out to 0 doesn't seem to trigger a show / hide where I expect it would with the minZoom and maxZoom settings.

I'm using markercluster version 1.0.5 and leaflet 1.0.3

Regards,
Chris

**Comment by danzel** [comment]
Can you please reproduce your issue on [Leaflet playground](http://playground-leaflet.rhcloud.com/), Plunker, or JSFiddle?

**Comment by ghybs** [comment]
Hi @larotech,

Please can you clarify what made you think there are `minZoom` and `maxZoom` options?

**Comment by larotech** [comment]
Hi, my assumptions are based off of using ESRI leaflet components quite a bit with the cluster options which has a dependency for markercluster. ESRI leaflet js components such as feature / dynamic / image layers with or without defined symbology also have the ability to show/hide based on a zoom min/max. If this isn't a part of markercluster can it be added?

**Comment by ghybs** [comment]
Hi @larotech,

If I understand correctly, you are using [ESRI Leaflet tools](https://github.com/Esri/esri-leaflet), which provide an [`L.esri.FeatureLayer`](https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html) with `minZoom` and `maxZoom` options.

Furthermore, ESRI provides an extra [`L.esri.Cluster.FeatureLayer`](https://github.com/Esri/esri-leaflet-cluster) plugin (which uses this repo as dependency), but which no longer offers these 2 options, as can be seen on its [documentation](https://esri.github.io/esri-leaflet/api-reference/layers/clustered-feature-layer.html), whereas its name seems to imply it is a special type of `L.esri.FeatureLayer`, so we could have expected it to have more functionalities, not less.

Since these `minZoom` and `maxZoom` options on ESRI Feature Groups are not part of Leaflet base (see [Layer Group](http://leafletjs.com/reference-1.0.3.html#layergroup) and [Feature Group](http://leafletjs.com/reference-1.0.3.html#featuregroup) options), hence are added by ESRI, it does not sound fair to expect them to be added to this Leaflet plugin.

In this situation, it seems to me that your feature request would be more appropriate on [`L.esri.Cluster.FeatureLayer`](https://github.com/Esri/esri-leaflet-cluster) repository.

Hope this helps.
