### ISSUE TITLE
MarkerCluster resets the sizes of the clustered markers

### ISSUE THREAD

**Issue by gembutterfly** [Leaflet/Leaflet.markercluster#786]
When clustering several markers, the size gets reseted to the default one.

- [ x] I'm reporting a bug, not asking for help
- [x ] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce
```javascript
var icon = plateMark.options.icon;
var size = 64 * entry.kJ / 8000;
icon.options.iconSize = [size, size];
plateMark.setIcon(icon);
```

- Leaflet version I'm using: 1.0.3
- Leaflet.MarkerCluster version I'm using: 1.0.5
- Browser (with version) I'm using: Firefox 53
- OS/Platform (with version) I'm using: Linux Ubuntu GNOME 16.04

## What behaviour I'm expecting and which behaviour I'm seeing

I expect the icons the stay the previously defined size.

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/beg/1/edit?html,output or any other jsfiddle like site.

**Comment by danzel** [comment]
Please include your reproduction case in the jsfiddle so we can run it and understand it.
Instruction on how to actually reproduce it too please thanks!

**Comment by gembutterfly** [comment]
Hi, here is a jsfiddle

http://playground-leaflet.rhcloud.com/kofeb/1/edit?html,js,output

**Comment by ghybs** [comment]
Hi,

This is absolutely not specific to Leaflet.markercluster, and this _might_ in a certain manner be a bug from Leaflet base, or more probably a matter of proper wording.

1. In your provided playground, you set `icon` from `marker` into `marker2` ("`marker2.setIcon(icon)`"), so no doubt both markers will have the same icon scaled by 0.5 (as applied on `icon` from `marker`).

2. Once this is corrected, both icons are still getting the same modified size (but this time the final size is scaled by 0.5 * 0.9), and this is reproducible with a simple Layer Group instead of a MarkerClusterGroup. Therefore nothing to do with Leaflet.markercluster plugin.

3. By changing some `options` from `icon` option of `marker`, this actually already affects the `icon` option of `marker2` as well (and from any other previously or later created marker). We can even check the equality of both icons (`marker.options.icon === marker2.options.icon` gives `true`).
This is the direct consequence of the [`L.Marker` class default `icon` option](https://github.com/Leaflet/Leaflet/blob/v1.0.3/src/layer/marker/Marker.js#L19-L21), which is set as a `new L.Icon.Default()`. This actually means that **all** markers without a specified `icon` will use that exact instance of `L.Icon.Default`.
I _think_ that is the [intended behaviour](https://github.com/Leaflet/Leaflet/pull/2800#issuecomment-49487087), but I feel its [description](http://leafletjs.com/reference-1.0.3.html#marker-icon) might be understood otherwise: "_If not specified, a new `L.Icon.Default` is used_" _may_ imply that a new instance is created for each marker…

That being said, you have several very simple workarounds:

- For each of your markers, at instantiation explicitly specify a new icon (possibly the default one: `L.marker(latLng, { icon: new L.Icon.Default() })`.
Updated playground: http://playground-leaflet.rhcloud.com/yimo/1/edit?html,output

- Patch `L.Marker` class so that its behaviour matches its `icon` option description (the way I described it above):
Updated playground: http://playground-leaflet.rhcloud.com/hiju/1/edit?html,output

```javascript
L.Marker.mergeOptions({
  icon: null
});

L.Marker.addInitHook(function () {
  if (!this.options.icon) {
    this.options.icon = new L.Icon.Default();
  }
});
```

Next time you might rather use Stack Overflow or GIS Stack Exchange first, to reach a wider audience and possibly get faster help.

**Comment by gembutterfly** [comment]
thanks for your help, guess thats been a stupid typo using icon instead of icon2 - which happened by simplifying my code into a tiny example. nevertheless, thank you very much - I'll try to extract where exactly this happens. In my other code, I use a new icon for every marker, they all have different sizes, until they get clustered. I'll try to provide another playground.
