### ISSUE TITLE
dynamic radius

### ISSUE THREAD

**Issue by lpinto-eu** [Leaflet/Leaflet.markercluster#803]
Would be great if it was possible to define the radius in realtime and in meters. This would allow for a user to be able to customize what hi (she) is seeing and how fine tuned.
What are your thoughts on this?

**Comment by danzel** [comment]
If you can implement this efficiently then yep sure :)

I think prunecluster has this, so maybe check that out as an alternative?
https://github.com/SINTEF-9012/PruneCluster

**Comment by lpinto-eu** [comment]
Sorry but I know nothing regarding clustering, that is why my issue is phrased as a question/request.
Could it be possible to have a zoom / radius relational table? Then if we could get a function to convert meters to pixel, we could do something similar.

**Comment by ghybs** [comment]
Hi @lpinto-eu,

> a function to convert meters to pixel

You should be able to do this using Leaflet [map conversion methods](http://leafletjs.com/reference-1.1.0.html#map-conversion-methods), probably a combination of `distance` and `latLngToContainerPoint`, having to make up 2 LatLng's (on same latitude) until you get your desired distance in meters.

This highlights BTW that a _meters_ specification for clustering radius would be somehow very strange. E.g. near the poles, 1 meter may take a lot of pixels, whereas on the equator, for the same zoom level, 1 pixel can represent a few hundreds meters.

As for _dynamically_ changing the clustering radius, it seems to me that a very easy way to achieve a similar result, the "brute" way, would be to create a new MCG whenever a different radius is desired. Add first the new one to the map, so that the clustering computation is performed, then remove the old one.
