### ISSUE TITLE
singleMarkerMode with refreshClusters

### ISSUE THREAD

**Issue by mad4hit** [Leaflet/Leaflet.markercluster#813]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.3
- Leaflet.MarkerCluster version I'm using: 1.0.6
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Windows 10

i'm setting the singleMarkerMode conditionally on the markerClusterGroup, if the zoom is < 16 i'll show the cluster icon, otherwise i want to show the marker icon.

To do that i call the  refreshClusters() function each time the dataset is changed, i've noticed that the function works from marker to clusterMarker but not the inverse.

## What behaviour I'm expecting and which behaviour I'm seeing
I'm expecting to see the marker change or don't change at all

## Minimal example reproducing the issue
- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

here a simple example:

http://playground-leaflet.rhcloud.com/zizu/1/edit?html,output

Regards
Alex

**Comment by ghybs** [comment]
Hi,

Thank you for the detailed explanations of what you are trying to achieve and for the playground!

Once MCG replaces your Marker icon by the "fake" cluster (when `singleMarkerMode` option kicks in), it overrides the Marker initial icon and dismisses any reference to it.

This explains why you cannot retrieve the initial icon back.

You might be able to implement your feature by using the [`iconCreateFunction`](https://github.com/Leaflet/Leaflet.markercluster#customising-the-clustered-markers) (instead of dynamically changing the `singleMarkerMode` option), detecting the zoom level and `getChildCount() === 1` and storing the initial Marker icon when you replace it, so that you can retrieve it later on when needed.

Hope this helps.

**Comment by danzel** [comment]
Thanks @ghybs 
I don't think this behaviour is likely to change unless we change how `singleMarkerMode` works.
