### ISSUE TITLE
Base icon covering first few generatePointsCircle() marker

### ISSUE THREAD

**Issue by TENsaga** [Leaflet/Leaflet.markercluster#875]
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## What behaviour I'm expecting and which behaviour I'm seeing

Hovering over the first few points generated by the spider circle, the on-hover popup text is blocked by the default faded cluster icon. 

As others have mentioned, you can bypass this by extending the distance of the legs to 2x multiplier, but we would like to keep the distance set at 1.

Are there any ways around this? (without touching the source code)

## Minimal example reproducing the issue

The image below is set to 1.5x distance:

![clustermarkerunclickable](https://user-images.githubusercontent.com/22858193/36510111-ca3f72c6-1716-11e8-83a4-263a6de361d7.png)

If you move the mouse slightly passed the icon, the popup text appears.

Thanks.

**Comment by ghybs** [comment]
Hi,

Which version of Leaflet.markercluster plugin are you using?

This issue is supposed to be fixed with PR https://github.com/Leaflet/Leaflet.markercluster/pull/846, shipped since [`v1.3.0`](https://github.com/Leaflet/Leaflet.markercluster/blob/master/CHANGELOG.md#130-2018-01-19).

With this version, no `spiderfyDistanceMultiplier` specified and with default Circle Marker radius of [10px](http://leafletjs.com/reference.html#circlemarker-radius), the first marker is not clickable on its right half, but its centre and left half are normally clickable.

Live example: https://plnkr.co/edit/Ldq4XiJa7UdnGWw9cUYN?p=preview
(you can uncomment the `spiderfyDistanceMultiplier` option to see the difference with your screenshot)

**Comment by TENsaga** [comment]
Ah, sorry about that, should have looked a little harder through previous issues.

Looks like the package.json semver blocked the update:

`"leaflet.markercluster": "~1.2.0",`

Thank you for the help
