### ISSUE TITLE
zoomToShowLayer doesn't fire callback when using CircleMarkers

### ISSUE THREAD

**Issue by NRaf** [Leaflet/Leaflet.markercluster#904]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Leaflet.MarkerCluster version I'm using: 1.3.0
- Browser (with version) I'm using: Chrome 67.0.3396.87
- OS/Platform (with version) I'm using: macOS High Sierra
- Add three circle markers to the map (in my case, 2 in Hong Kong and 1 in the Phillipines - see example).
- Zoom out so all three markers cluster together.
- Call `zoomToShowLayer` passing the Phillipines marker.

## What behaviour I'm expecting and which behaviour I'm seeing

Expecting the `zoomToShowLayer` callback to be fired. It's not fired because it's checking for an icon on the marker before firing the callback, which doesn't exist on a CircleMarker. The Hong Kong buttons because the parent (i.e. the cluster) has an icon.

`if ((layer._icon || layer.__parent._icon) && !this._inZoomAnimation) {`

## Minimal example reproducing the issue

Clicking on `Zoom to Marker 1` doesn't open the popup.
http://jsfiddle.net/7cxwu248/28/

**Comment by danzel** [comment]
It does work for marker 2 and 3 though, which look to be equivalent other than location as far as I can tell?
Weird bug though.

**Comment by ghybs** [comment]
Hi,

Seems that it works for spiderfied Circle Markers (i.e. Markers 2 and 3 in the provided example) because in that case the callback is executed once `"spiderfied"` event fires, whether the Layer has an `_icon` or not.
https://github.com/Leaflet/Leaflet.markercluster/blob/4cea2dfba189972c7ce06a0ab3cbc9cc8aa0b694/src/MarkerClusterGroup.js#L544-L556

Since the check for `layer._icon` and `layer.__parent._icon` is to know whether they are visible (added) on map or not, we could simply use [`map.hasLayer`](https://leafletjs.com/reference-1.3.0.html#map-haslayer) instead (if it is not on map, it is collected in a cluster, or not part of this cluster group at all…)

Updated JSFiddle: https://jsfiddle.net/7cxwu248/39/

BTW this is the same case on the next lines:
https://github.com/Leaflet/Leaflet.markercluster/blob/4cea2dfba189972c7ce06a0ab3cbc9cc8aa0b694/src/MarkerClusterGroup.js#L558-L560
It is less of a problem, since in this case we move first then execute the callback, instead of just executing the callback.

**Comment by mirko77** [comment]
The CDN version still has the old code or am I missing something?

https://unpkg.com/browse/leaflet.markercluster@1.4.1/dist/leaflet.markercluster-src.js

**Comment by mirko77** [comment]
Well, version 1.4.1 still has the `_icon` check, the following is from sources:

```

zoomToShowLayer: function (layer, callback) {

		if (typeof callback !== 'function') {
			callback = function () {};
		}

		var showMarker = function () {
			if ((layer._icon || layer.__parent._icon) && !this._inZoomAnimation) {
				this._map.off('moveend', showMarker, this);
				this.off('animationend', showMarker, this);

				if (layer._icon) {
					callback();
				} else if (layer.__parent._icon) {
					this.once('spiderfied', callback, this);
					layer.__parent.spiderfy();
				}
			}
		};

		if (layer._icon && this._map.getBounds().contains(layer.getLatLng())) {
			//Layer is visible ond on screen, immediate return
			callback();
		} else if (layer.__parent._zoom < Math.round(this._map._zoom)) {
			//Layer should be visible at this zoom level. It must not be on screen so just pan over to it
			this._map.on('moveend', showMarker, this);
			this._map.panTo(layer.getLatLng());
		} else {
			this._map.on('moveend', showMarker, this);
			this.on('animationend', showMarker, this);
			layer.__parent.zoomToBounds();
		}
	},

```

**Comment by ghybs** [comment]
You could patch the library using Leaflet class `include`, as done in the above updated JSFiddle.

**Comment by mirko77** [comment]
I downloaded the sources and made my changes, I just realized this repo is not maintained anymore.
