### ISSUE TITLE
enableClusteringAtZoom

### ISSUE THREAD

**Issue by astomas** [Leaflet/Leaflet.markercluster#948]
Hi
I enable a cluster at zoom value >=19 and remove it when zooming out to 18, 17 etc.: map.removeLayer(myClusterGroup) on "zoomend" event.
It works ok, however, icons that are no part of a cluster or previously spiderfied disappear when zooming out to 18, 17 etc. and reappear at zoom 19 and more. There is no console error to trace it. 
Any idea why?
Thx

**Comment by danzel** [comment]
You shouldn't call removeLayer with a cluster, only with markers.

**Comment by ghybs** [comment]
Hi @astomas,

If I understand correctly, you have several Markers in your Cluster Group which are not clustered because they are far enough from other Markers. Therefore you see their icon, whereas clustered ones are "hidden" under cluster bubbles.

Then you remove the Cluster Group from the map and wonder why the non clustered Markers also disappear.

In that case, it works as designed: even though you see non clustered Markers, you have explicitly added them to your Cluster Group. Therefore when you remove the latter, it removes all its child Markers, even those which are currently not clustered.

**Comment by astomas** [comment]
thanks. I wil look into that and give feedback if useful.
